#include "cli.h"

static const char *const app_guide[] = {
  "charts -- DOS-style chart decks for the Linux console.  A tool for agents.\n",
  "\n",
  "You (the agent) build a deck: one JSON file of slides holding charts, text and\n",
  "big numbers, plus the CSV files it draws from.  The human never runs charts or\n",
  "reads this.  They run a LAUNCHER you generate, page through with the arrow\n",
  "keys, fix numbers in a built-in spreadsheet, pin notes on bars.  Everything\n",
  "about how the deck looks is in the deck file; there are no flags to remember.\n",
  "\n",
  "The look is fixed and deliberate: 16 VGA colours, hard pixels, dithered\n",
  "shading, a bitmap font, double-line frames, drop shadows.  1991 business\n",
  "graphics.  On the bare console it is drawn in real pixels through the\n",
  "framebuffer; in kitty/ghostty/wezterm/foot through their graphics protocols;\n",
  "anywhere else in half-block characters.  charts works out which at run time.\n",
  "\n",
  "==============================================================================\n",
  "THE LOOP\n",
  "==============================================================================\n",
  "  1. DATA      one tidy CSV per chart beside the deck: header row, one label\n",
  "               column, one numeric column per series.  Aggregate, sort and\n",
  "               round upstream (SQL, awk, python); charts draws what it is given.\n",
  "  2. DECK      write deck.json (format below).\n",
  "  3. CHECK     charts deck.json --check\n",
  "               Every problem with its JSON path and a did-you-mean.  It also\n",
  "               DRAWS every slide at console size and warns about whatever did\n",
  "               not fit (title cut, labels thinned, ylabel too long, annotation\n",
  "               naming a category that is not in the data).  Exit 1 = errors.\n",
  "               Get it to zero warnings.\n",
  "  4. LOOK      charts deck.json --png-dir DIR     then open every PNG.\n",
  "               Valid is not the same as good.  Only the picture shows a callout\n",
  "               on the wrong bar, a pie of 14 slivers, a slide that says nothing.\n",
  "               Each PNG is pixel-for-pixel the human's screen, a few KB.\n",
  "  5. LAUNCHER  charts deck.json --launcher NAME\n",
  "               Writes ~/.local/bin/NAME (or the path, if NAME has a slash) and\n",
  "               prints it: a small POSIX sh script, a command with no .sh on\n",
  "               it.  Give the human the command and the path it printed; that\n",
  "               is all they need.  The launcher finds charts, opens a terminal\n",
  "               if started without one (menu, key binding), and charts picks\n",
  "               framebuffer / kitty / sixel / cells from where it finds itself.\n",
  "  If the human already has the deck open, skip 5: the presenter watches the\n",
  "  deck and its data files and redraws when you rewrite them.\n",
  "\n",
  "  charts deck.json --describe      the outline as parsed (slides, blocks, rows x series)\n",
  "  charts data.csv --describe       how a data file's columns were read\n",
  "  charts deck.json --check --json  {\"ok\",\"slides\",\"errors\",\"warnings\",\"issues\":[{\"level\",\"path\",\"message\"}]}\n",
  "  charts deck.json --print --slide 2     a slide as text (for a log or a reply)\n",
  "  charts data.csv -t line --png c.png    one chart, no deck\n",
  "  charts --example deck            a working deck to start from\n",
  "  Exit status: 0 fine (warnings allowed), 1 the input has errors, 2 bad usage.\n",
  "\n",
  "==============================================================================\n",
  "DECK\n",
  "==============================================================================\n",
  "{\n",
  "  \"title\":   \"shown in the footer bar and the slide overview\",\n",
  "  \"footer\":  \"replaces title in the footer bar\",\n",
  "  \"theme\":   \"dos\" | \"black\" | \"light\" | { custom, see THEMES },\n",
  "  \"palette\": \"dos\" | ... | [\"yellow\", \"cyan\", ...]      see PALETTES\n",
  "  \"display\": {\"gfx\": \"auto\", \"scale\": 2, \"size\": [120, 33], \"ascii\": false, \"color\": true},\n",
  "  \"slides\":  [ SLIDE, ... ]                              required\n",
  "}\n",
  "Paths are relative to the deck file.  JSON has no comments: keys starting with\n",
  "\"_\" are ignored, put notes to yourself there.  Unknown keys are warnings.\n",
  "\n",
  "SLIDE\n",
  "  {\"title\": \"...\", \"subtitle\": \"...\", \"notes\": \"speaker notes (key n)\",\n",
  "   \"layout\": \"auto\" | \"cols\" | \"rows\" | \"grid\",  \"blocks\": [ BLOCK, ... ]}\n",
  "  no blocks    a title slide: title triple size and centred, subtitle under a rule\n",
  "  one block    write its keys straight on the slide (the common case):\n",
  "               {\"title\": \"Revenue by month\", \"type\": \"line\", \"data\": \"rev.csv\"}\n",
  "\n",
  "BLOCK   the key it has decides what it is\n",
  "  chart   {\"data\": \"file.csv\" | INLINE, \"type\": \"bar\", ...CHART FIELDS}\n",
  "  text    {\"text\": \"line\\nline\" | [\"line\", ...]}   or   {\"bullets\": [\"...\", ...]}\n",
  "          line markup:  \"# heading\"  \"## subheading\"  \"- bullet\"  \"> aside (dim)\"  \"**emphasis**\"\n",
  "          \"size\": 1-4 (cell height of the text)   \"align\": left|center|right\n",
  "          \"valign\": top|middle    \"color\": COLOUR    \"box\": true (framed window; \"title\" in the frame)\n",
  "          One string per bullet or paragraph; long lines wrap with a hanging indent.\n",
  "  stat    {\"stat\": \"1,153\", \"label\": \"signups, W35\", \"delta\": \"+8.5% w/w\", \"color\": COLOUR}\n",
  "          one big number.  delta starting \"+\" is green with an up arrow, \"-\" red and down.\n",
  "  flow    {\"flow\": [\"read\", \"think\", \"write\"], ...}      boxes and arrows, laid out for you\n",
  "  shapes  {\"shapes\": [SHAPE, ...]}                       free drawing       see DIAGRAMS\n",
  "  group   {\"cols\": [BLOCK, ...]}  or  {\"rows\": [BLOCK, ...]}     nests to any depth\n",
  "  any     \"weight\": 2            share of its row/column (default 1)\n",
  "          \"at\": [x, y, w, h]     explicit place on a 12 x 12 grid over the slide body\n",
  "          \"like\": 3              start from slide 3's chart (or \"slides[2].blocks[0]\"):\n",
  "                                 every key of it, then this block's own keys win.\n",
  "                                 Two slides, one chart written once: the BUILD.\n",
  "\n",
  "LAYOUT   auto = up to three blocks side by side, more in a grid.  cols / rows /\n",
  "  grid force it.  \"at\" ignores layout.  The dashboard slide:\n",
  "     {\"cols\": [stat, stat, stat], \"at\": [0, 0, 12, 3]},\n",
  "     {\"data\": \"x.csv\", \"type\": \"stacked\", \"at\": [0, 3, 8, 9]},\n",
  "     {\"text\": [\"# What happened\", \"- ...\"], \"at\": [8, 3, 4, 9]}\n",
  "\n",
  "==============================================================================\n",
  "CHART FIELDS   (all optional; all also valid in a data file's own chart block)\n",
  "==============================================================================\n",
  "  type       bar stacked hbar dumbbell line area pie pie3d donut scatter hist table\n",
  "  title subtitle xlabel ylabel\n",
  "  values     numbers on the bars / points          (default false)\n",
  "  legend grid shadow                               (default true)\n",
  "  frame      double | single | heavy | none\n",
  "  depth      0..6  3-D extrusion of bars, pies, donuts; 0 = flat   (default 2)\n",
  "  explode    pie: 0-based row to pop out, or true = the biggest\n",
  "  palette    name or list, for this chart only\n",
  "  colors     pin colours by name, or in order:\n",
  "               {\"revenue\": \"green\", \"costs\": \"red\"}     by series name\n",
  "               {\"Dec\": \"white\"}                          one bar of a single-series bar/hbar\n",
  "               {\"ok\": \"green\", \"down\": \"red\"}            pie slices by label\n",
  "               [\"grey\", \"yellow\"]                        in series order\n",
  "  min max    pin the value axis (max gets its own tick).  Bars on an axis that\n",
  "             does not start at zero are drawn torn, with a break in the axis.\n",
  "  prec       decimals in value labels and tables (default: as the CSV wrote them)\n",
  "  bins       histogram buckets (default 10)\n",
  "  xy         first numeric column is the X axis (scatter; line over numeric X)\n",
  "  errors     whiskers from other columns: {\"tg\": \"tg sd\"} (+-), {\"tg\": [\"min\", \"max\"]},\n",
  "             or \"sd\" / [\"min\", \"max\"] for the first series.  bar hbar line scatter.\n",
  "  transpose no_header labels_col series_col label_key delim     how to read the file\n",
  "             series_col N keeps only column N as the series: one file, many charts.\n",
  "             Columns count from 1 WITH the labels: in \"name,a,b\" a is 2, b is 3.\n",
  "             Columns that errors names are kept too.  --describe shows the numbers.\n",
  "  annotations  [ ... ]  see ANNOTATIONS\n",
  "\n",
  "  Which type:\n",
  "    compare categories ................ bar      (hbar: long names, rankings)\n",
  "    before -> after, per category ..... dumbbell (a series per state: \"1 GbE\", \"2.5 GbE\")\n",
  "    parts of a total per category ..... stacked\n",
  "    change over time .................. line     (area: 1-2 series where volume matters)\n",
  "    share of one total, <= 6 parts .... pie3d / donut    (more parts: hbar)\n",
  "    two measures against each other ... scatter + xy\n",
  "    spread of one measure ............. hist\n",
  "    the exact numbers ................. table    (text columns too, numbers as written)\n",
  "    how something works ............... flow     (see DIAGRAMS)\n",
  "  A pie of one series has a slice per row; of several series, a slice per series.\n",
  "\n",
  "COLOUR  a name or 0..15:  black blue green cyan red magenta brown yellow white\n",
  "  grey, each also \"dark X\" (dark grey, dark red ...).  Plain names are the\n",
  "  bright ones; brown is dark yellow.  16 colours is all there is: shading is\n",
  "  dither, never a 17th colour.\n",
  "\n",
  "DATA   a CSV/TSV/JSON file, or inline in any of these shapes:\n",
  "  {\"labels\": [\"Q1\",\"Q2\"], \"series\": [{\"name\": \"north\", \"values\": [120, 145]}, ...]}\n",
  "  [{\"label\": \"Q1\", \"north\": 120, \"south\": 88}, ...]\n",
  "  {\"payroll\": 620, \"cloud\": 310}             {\"x\": [1,2,3], \"y\": [4,5,6]}\n",
  "  [[\"\", \"north\", \"south\"], [\"Q1\", 120, 88], ...]        null = a gap\n",
  "  CSV: delimiter , ; TAB | is sniffed; '#' lines are comments; plain numbers\n",
  "  only (1234.5 -3 1e6 $12 12%; \"1,234\" only quoted; no other units); an empty\n",
  "  field is a gap, and so is a stray word in a numeric column (--check names it).  Columns of words are shown by a table, ignored by\n",
  "  every other chart.\n",
  "  A file can say how it is drawn:   #chart: type=line, title=\"Load\", values\n",
  "                                    {\"chart\": {\"type\": \"pie3d\"}, \"rows\": [...]}\n",
  "  Precedence: command line > deck > data file > defaults.\n",
  "  Use files when the human may edit the numbers: the sheet saves CSVs in place\n",
  "  (comment and #chart lines kept) and inline data back into the deck.\n",
  "\n",
  "ANNOTATIONS   say what the chart means, on the chart\n",
  "  {\"at\": \"Apr\", \"series\": \"revenue\", \"text\": \"spring launch\"}   callout + leader to a point (pie: a slice)\n",
  "  {\"y\": 150, \"text\": \"target\"}                                  dashed line across the plot\n",
  "  {\"x\": \"Apr\", \"text\": \"price change\"}                          dashed line up the plot\n",
  "  {\"note\": [0.02, 0.02], \"text\": \"n = 412\"}                     free text, [x,y] 0..1 from top left\n",
  "  \"at\"/\"x\" = the category label as in the data (or a 0-based row); \"series\"\n",
  "  optional.  On a scatter \"x\" is a value on the X axis.  \"color\": COLOUR\n",
  "  recolours one.  Text wraps at 24 characters.\n",
  "  Callouts place themselves clear of value labels and each other.  On hbar\n",
  "  and dumbbell the value axis runs across, so \"y\" stands up and \"x\" lies down.\n",
  "\n",
  "==============================================================================\n",
  "DIAGRAMS   -- when the point is how something works, not how much\n",
  "==============================================================================\n",
  "FLOW   boxes and arrows, laid out for you.  Name the steps; never a coordinate.\n",
  "  {\"flow\": [\"tokens\", \"CUDA0\", {\"id\": \"yoda\", \"text\": \"yoda\\n2 GPUs\", \"color\": \"red\"}, \"CUDA1\"],\n",
  "   \"labels\": {\"yoda>CUDA1\": \"1 MB/token\"}}             a chain, in the listed order\n",
  "  \"edges\": [[\"a\", \"b\"], [\"a\", \"c\", \"label\"], {\"from\": \"c\", \"to\": \"d\", \"dash\": true, \"color\": \"red\"}]\n",
  "                                                       any graph instead: fans, joins, loops\n",
  "  \"dir\": \"down\"          stack the steps (default: left to right)\n",
  "  \"box\": true            in a window of its own, \"title\" in the frame\n",
  "  A step is a string, or {\"id\", \"text\", \"color\"}; \"\\n\" breaks its text.  A\n",
  "  coloured step is solid; a plain one is a window like the rest.\n",
  "\n",
  "SHAPES   free drawing on a 12 x 12 grid over the block (fractions fine):\n",
  "  {\"rect\": [x, y, w, h]}   {\"ellipse\": [x, y, w, h]}   {\"poly\": [[x, y], ...]}\n",
  "  {\"line\": [[x, y], ...]}  {\"arrow\": [[x, y], ...]}    {\"label\": [x, y], \"text\": \"...\"}\n",
  "  \"text\"        inside a closed shape, above a line's middle\n",
  "  \"color\"       a solid fill (a plain shape is a DOS window: panel inside, frame round)\n",
  "  \"border\" COLOUR  \"fill\": false  \"dither\": 1-3  \"depth\": 0-6  \"shadow\": true\n",
  "  \"width\": 1-4  \"dash\": true  \"head\": end|start|both|none  \"size\": 1-3 (text)\n",
  "  \"text_color\" COLOUR   \"align\": left|center|right (labels)\n",
  "  Later shapes draw over earlier ones.  The grid is the block's, so a shapes\n",
  "  block in a column is drawn in that column's proportions.\n",
  "\n",
  "==============================================================================\n",
  "THEMES, PALETTES, DISPLAY   -- everything about presentation is in the file\n",
  "==============================================================================\n",
  "THEMES   \"dos\"    blue desktop, black chart windows, grey status bar (default)\n",
  "         \"black\"  no backdrop at all          \"light\"  grey desktop, white windows\n",
  "  Custom: an object.  Start from a base and recolour any part:\n",
  "  \"theme\": {\"base\": \"black\", \"slide_bg\": \"black\", \"panel_bg\": \"black\", \"frame\": \"brown\",\n",
  "            \"title\": \"yellow\", \"heading\": \"yellow\", \"text\": \"brown\", \"axis\": \"brown\", ...}\n",
  "    slide_bg   the desktop (\"none\" = leave the terminal's own background)\n",
  "    panel_bg   inside chart / stat / boxed-text windows\n",
  "    frame      window borders                 accent    focus ring, ## subheadings, **emphasis**\n",
  "    title      chart titles in the frame      heading   slide titles, # headings\n",
  "    subtitle   chart subtitles                text      body text on the desktop\n",
  "    dim        slide subtitles, > asides      bullet    the bullet squares\n",
  "    axis tick grid label xlabel ylabel legend value     the parts of a plot\n",
  "    bar_fg bar_bg bar_key                     the footer bar, and the key hints in it\n",
  "    note_fg note_bg                           annotation callouts\n",
  "    table_head table_rule table_row           tables and the data sheet\n",
  "    cursor_fg cursor_bg                       the sheet's cell cursor\n",
  "  Series colours that match panel_bg are skipped; on a light panel bright\n",
  "  colours are swapped for their dark partners so they stay readable.\n",
  "\n",
  "PALETTES  series colours, in order\n",
  "  dos    yellow cyan green red magenta blue white ...   (default)\n",
  "  ega    red green yellow blue magenta cyan ...         cga    cyan magenta white yellow\n",
  "  ice    cyans, blues, white        fire   yellow red brown       green  phosphor greens\n",
  "  amber  amber terminal             mono   white/grey, series told apart by DITHER\n",
  "  Custom: a list.  \"palette\": [\"yellow\", \"brown\", \"white\", \"dark grey\"]\n",
  "  Deck-level sets the default; a chart's own \"palette\" or \"colors\" overrides.\n",
  "\n",
  "DISPLAY   \"display\": {...} in the deck; the launcher needs no flags\n",
  "  gfx     auto (default) | fb | kitty | sixel | cells | ascii | vga (DOS)\n",
  "  scale   pixel multiplier on pixel displays.  auto = screen width / 960, so a\n",
  "          1080p console is scale 2 = a 120 x 33 cell slide.  1 = twice as much\n",
  "          room (240 x 67) and half-size text; 3 = a big-print 80 x 22.\n",
  "  size    [cols, rows] for --png and --print (default 120 x 33; DOS 80 x 29)\n",
  "  ascii   true = plain ASCII only          color   false = no colour (dither instead)\n",
  "  Design for 120 x 33 unless you set scale; --check and --png use the same grid.\n",
  "  On DOS the screen is VGA, 80 x 29 cells for the slide: design for that.\n",
  "\n",
  "==============================================================================\n",
  "WHAT FITS   (120 x 33 cells; text that does not fit is cut, never shrunk)\n",
  "==============================================================================\n",
  "  slide title ........ 55 characters\n",
  "  category labels .... share the plot width.  Full-width chart: 12 labels of\n",
  "                       <= 6 chars, or 6 of <= 14.  Two-thirds width: 4 of <= 10.\n",
  "                       Longer -> hbar (labels get up to a third of the chart),\n",
  "                       or shorten in the CSV (\"qwen-27b\", \"Q1 25\").\n",
  "  ylabel ............. one letter per row down the axis: ~18 chars on a\n",
  "                       full-height chart, ~12 under a KPI strip.  xlabel: the chart's width.\n",
  "  series ............. up to ~6.   pie slices: up to ~6, then hbar.\n",
  "  side column text ... a third of the slide = ~35 chars a line, ~20 lines.\n",
  "                       A \"# heading\" there is double size up to 17 chars, normal beyond.\n",
  "  stat ............... value <= 6 chars draws large; label <= 30 in a third-width tile\n",
  "  values: true ....... good to ~12 categories x 2 series; numbers that do not fit are dropped\n",
  "  line charts ........ ~40 points.   hist: up to 60 bins.\n",
  "  characters ......... Latin, Greek, Cyrillic, box drawing.  CJK and emoji are two\n",
  "                       cells wide and not in the font: drawn as ?, and --check says where.\n",
  "  flow ............... ~5 steps across a full-width slide, more with \"dir\": \"down\";\n",
  "                       an arrow label as wide as the gap it names, ~12 characters.\n",
  "\n",
  "==============================================================================\n",
  "CRAFT   the look is fixed; whether a slide says something is up to you\n",
  "==============================================================================\n",
  "  TITLE = THE TAKEAWAY.  \"Signups are up 70% since week 27\", not \"Signups\".\n",
  "    The deck should tell its story through the titles alone.\n",
  "  ONE IDEA PER SLIDE.  A chart and 2-4 bullets, or a KPI strip over a chart.\n",
  "    More than that is another slide.\n",
  "  AN ARC.  Title slide -> the headline number -> how we got there -> the\n",
  "    exception -> what it cost -> the receipts (tables) -> what to do next.\n",
  "  COLOUR IS MEANING, NOT DECORATION.  Grey out the context and light up the\n",
  "    one thing:  \"colors\": {\"West\": \"yellow\", \"North\": \"grey\", \"South\": \"dark grey\"}.\n",
  "    One bar in a ranking:  \"colors\": {\"Dec\": \"white\"}.  Status colours on a\n",
  "    pie: green / yellow / red.  Red and green annotations for bad and baseline.\n",
  "  ANNOTATE THE CLAIM.  If the title says June was the problem, put a callout\n",
  "    on June.  at = the point, y = the target or threshold, x = the moment\n",
  "    something changed, note = sample size and caveats.  One to three per chart.\n",
  "  BUILDS.  Two slides, the same chart: first quiet (grey, no notes), then\n",
  "    again with the annotations and the conclusion as its title.  Write it\n",
  "    once and say \"like\": 3 on the second.  Pin min/max so nothing jumps.\n",
  "  SHOW THE SPREAD.  When the data has one (llama-bench's +-, min/max over\n",
  "    runs), put it on the chart with errors: a gap that is inside the noise\n",
  "    is not a finding.\n",
  "  EXPLAIN THE MECHANISM.  When a finding has a cause, a flow of 3-5 boxes\n",
  "    with the arrow that matters labelled (\"1 MB/token over 1 GbE\") beats a\n",
  "    paragraph.  Colour the box where the cost is.\n",
  "  SMALL MULTIPLES.  layout grid + series_col to split one file into a panel\n",
  "    per series, the SAME min/max on every panel, one panel in another colour.\n",
  "  PIN THE AXIS when slides or panels are compared (min/max), and when a chart\n",
  "    should start at zero or stop at a meaningful ceiling (100%, a quota).\n",
  "  EXPLODE the slice you are talking about.  DEPTH 3-4 for a hero chart alone\n",
  "    on a slide, 1 or 0 for small panels and dense data.\n",
  "  KPI STRIP.  Three stat tiles across the top (\"at\": [0,0,12,3]); deltas with\n",
  "    + and - colour themselves.  A slide of only stats makes a strong opener.\n",
  "  BOXED TEXT (\"box\": true) sits beside a chart as an equal; plain text reads\n",
  "    as commentary.  \"size\": 2 text for a closing slide of 3-5 short lines.\n",
  "  THEME AND PALETTE SET THE MOOD.  dos = the boardroom.  black + amber or\n",
  "    green palette = the terminal.  light = paper.  A custom theme in two or\n",
  "    three colours (one hue + white + grey) looks designed; all 16 at once\n",
  "    looks like a test card.  mono when it may be printed.\n",
  "  NOTES.  Put what the presenter should say in \"notes\"; the human presses n.\n",
  "  SORT rankings descending, order time left to right, keep category order the\n",
  "    same on every slide.\n",
  "\n",
  "  The human, in the presenter:  arrows/space page, o overview, n notes, tab\n",
  "  focus, e edit data (a spreadsheet) or text, a annotate, t/p/v/l/g/d/x change\n",
  "  type/palette/values/legend/grid/depth/explode, i/c/N/E/X add text/chart/\n",
  "  slide, edit title, delete block, y theme, s save, r reload, q quit.  Their\n",
  "  edits land in the same files: re-read the deck and CSVs before changing them.\n",
  "\n",
  "==============================================================================\n",
  "WHEN SOMETHING IS OFF\n",
  "==============================================================================\n",
  "  \"cannot open\" ............ data paths are relative to the DECK, not your cwd\n",
  "  \"no numeric columns\" ..... units or thousands separators in the CSV; write plain numbers\n",
  "  \"series_col N is ...\" .... it counts the labels as column 1; the message lists the series\n",
  "  wrong labels / series .... charts file.csv --describe; then labels_col / series_col / transpose\n",
  "  numeric categories ....... a first column of years, sizes or counts is read as a SERIES.\n",
  "                             Say \"labels_col\": 1 to make it the categories, or \"xy\": true for a numeric X axis.\n",
  "  labels thinned or cut .... too many or too long: hbar, shorter names, fewer categories\n",
  "  annotation not drawn ..... \"at\" must match a label in the data exactly (--check says which)\n",
  "  error bars not drawn ..... errors names a column the data does not have (--check says which)\n",
  "  a chart is an error box .. the block's error is printed in place; --check has the path\n",
  "\n",
  "OPTIONS  (agents only; the launcher passes none)\n",
  "  --check [--json]   --describe   --png FILE   --png-dir DIR   --print   --slide N\n",
  "  --launcher NAME    --example [csv|json|deck]   -o FILE   -i (open data files in the presenter)\n",
  "  --demo             present a built-in deck (every feature, no files)\n",
  "  -t TYPE  -T TITLE  -p PALETTE  --theme NAME  --values --legend --grid --shadow (--no-...)\n",
  "  --frame S  --depth N  --explode [N]  --min V --max V  --prec N  --bins N\n",
  "  -w N -H N --size CxR  --scale K  --gfx MODE  --ascii  --no-color  --tile\n",
  "  --xy --transpose --no-header --delim C --labels-col N --series-col N --label-key K\n",
  "  --list-types --list-palettes --list-themes --version\n",
  "  Environment: CHARTS_GFX, CHARTS_FB (default /dev/fb0), NO_COLOR.\n",
  NULL
};

void app_print_help(FILE *f) { size_t i; for(i=0;app_guide[i];i++) fputs(app_guide[i],f); }
void app_print_schema(FILE *f) { app_print_help(f); }
