#!/usr/bin/env python3
"""Generate src/font_data.inc from tools/unscii-16.hex.

unscii is by Viznut and is in the public domain (http://viznut.fi/unscii/).
Only 8x16 glyphs from the blocks a chart needs are kept, so the table stays
small.  Re-run after changing RANGES:  python3 tools/mkfont.py
"""
import os

RANGES = [
    (0x0020, 0x007E),  # ASCII
    (0x00A0, 0x00FF),  # Latin-1
    (0x0100, 0x017F),  # Latin Extended-A
    (0x0391, 0x03C9),  # Greek
    (0x2010, 0x2027),  # dashes, quotes, bullets, ellipsis
    (0x2030, 0x203A),
    (0x2070, 0x209C),  # super / subscripts
    (0x20AC, 0x20AC),  # euro
    (0x2122, 0x2122),
    (0x2190, 0x21FF),  # arrows
    (0x2200, 0x22FF),  # maths
    (0x2300, 0x23FF),
    (0x2500, 0x259F),  # box drawing, blocks
    (0x25A0, 0x25FF),  # geometric shapes
    (0x2600, 0x26FF),
    (0x2700, 0x27BF),  # check marks, dingbats
]

here = os.path.dirname(os.path.abspath(__file__))
glyphs = {}
with open(os.path.join(here, "unscii-16.hex")) as f:
    for line in f:
        cp, _, bits = line.strip().partition(":")
        if len(bits) != 32:  # 8 px wide only
            continue
        cp = int(cp, 16)
        if any(lo <= cp <= hi for lo, hi in RANGES):
            glyphs[cp] = bits

out = os.path.join(here, "..", "src", "font_data.inc")
with open(out, "w") as f:
    f.write("// Generated by tools/mkfont.py from unscii-16 (public domain). Do not edit.\n")
    f.write("// {codepoint, 16 rows, MSB = leftmost pixel}, sorted by codepoint.\n")
    for cp in sorted(glyphs):
        b = glyphs[cp]
        rows = ",".join("0x" + b[i:i + 2] for i in range(0, 32, 2))
        f.write("{0x%04X,{%s}},\n" % (cp, rows))
print("%d glyphs -> %s" % (len(glyphs), os.path.normpath(out)))
